config/routes.rb
Chrysalis::Application.routes.draw do
  resources :pull_requests do
    member do
      post 'rebuild'
      get 'build_log'
      get 'app_log'
    end
  end

  resources :repos

  root :to => 'application#index'

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  has_many :pull_requests, dependent: :destroy, order: "github_updated_at ASC"

  validates_presence_of :name, :owner

  attr_accessible :name,
                  :owner,
                  :token,
                  :client_id,
                  :client_secret,
                  :github_status,
                  :jira_url,
                  :should_provision_mysql,
                  :should_provision_nginx,
                  :should_provision_redis,
                  :nginx_template,
                  :redis_template,
                  :log_file,
                  :jira_username,
                  :jira_password

  def self.sync_all_with_jira
    all.each do |repo|
      next unless !!repo.jira_url # skip if this repo isn't configured for jira

      client = repo.jira_client
      repo.pull_requests.each do |pull_request|
        begin
          pull_request.sync_with_jira(client)
        rescue
          Rails.logger.warn($!.to_s)
        end
      end
    end
  end

  def self.sync_all_with_github
    all.each do |repo|
      begin
        repo.clone_into_cached_copy

        github = Github.new(oauth_token: repo.token)

        # Get first 100 open pull requests for this repo
        open_pulls = github.pull_requests.list(repo.owner, repo.name, per_page: 100)
        open_pulls.each do |pull|
          # Check if this pull request is already in the db
          existing_pull = repo.pull_requests.where(number: pull.number).first

          # If it's new, save to the db
          if existing_pull.nil?
            new_pull = repo.new_pull_from_api(pull)
            new_pull.delayed_build

            if !!repo.jira_url
              # Comment on the jira issue
              client = repo.jira_client
              new_pull.comment_on_jira_issue(client, "A pull request has been created for this issue: #{new_pull.url}")
            end
          else
            # If the remote pull request has been updated, save and check back out
            if DateTime.parse(pull.updated_at) > existing_pull.updated_at
              existing_pull.update_attributes(
                title: pull.title,
                github_updated_at: pull.updated_at
              )
              existing_pull.checkout

              # if it was failed, rebuild with the updated code
              existing_pull.delayed_build if 2 == existing_pull.status
            end
          end
        end

        # Delete any previously saved pull requests that are no longer open
        open_pull_numbers = open_pulls.map(&:number)
        repo.pull_requests.each { |pr| pr.destroy if !open_pull_numbers.include?(pr.number) }
      rescue
        # Set the error status
        repo.update_attributes(github_status: 2)
        raise $!
      end

      # Set the success status
      repo.update_attributes(github_status: 1)
    end
  end

  def jira_client
    options = {
                :username => jira_username,
                :password => jira_password,
                :use_ssl => false,
                :context_path => '/',
                :site     => jira_url,
                :auth_type => :basic
              }

    JIRA::Client.new(options)
  end

  def clone_url
    "git@github.com:#{owner}/#{name}.git"
  end

  def clone_into_cached_copy
    system("git clone #{clone_url} #{cached_copy}") if !Dir.exists?(cached_copy)
  end

  def new_pull_from_api(pull)
    new_pull = PullRequest.new
    new_pull.repo = self
    new_pull.number = pull.number
    new_pull.url = pull.html_url
    new_pull.title = pull.title
    new_pull.user_login = pull.user.login
    new_pull.user_avatar_url = pull.user.avatar_url
    new_pull.github_created_at = pull.created_at
    new_pull.github_updated_at = pull.updated_at
    new_pull.head_ref = pull.head.ref
    new_pull.head_sha = pull.head.sha
    new_pull.status = 3 # not started
    new_pull.save
    new_pull
  end

  def cached_copy
    Rails.root.join("builds", "#{owner}-#{name}-cached-copy")
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all

    respond_to do |format|
      format.json { render json: @repos.to_json(include: :pull_requests) }
    end
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
    @repo = Repo.find(params[:id])

    respond_to do |format|
      format.json { render json: @repo.to_json(include: :pull_requests) }
    end
  end

  # GET /repos/new
  # GET /repos/new.json
  def new
    @repo = Repo.new

    respond_to do |format|
      format.json { render json: @repo }
    end
  end

  # GET /repos/1/edit
  def edit
    @repo = Repo.find(params[:id])
  end

  # POST /repos
  # POST /repos.json
  def create
    params[:repo].delete(:pull_requests)
    @repo = Repo.new(params[:repo])

    respond_to do |format|
      if @repo.save
        format.json { render json: @repo, status: :created, location: @repo }
      else
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repos/1
  # PUT /repos/1.json
  def update
    blacklist = [:pull_requests, :created_at, :updated_at]
    blacklist.each { |field| params[:repo].delete(field) }

    @repo = Repo.find(params[:id])

    respond_to do |format|
      if @repo.update_attributes(params[:repo])
        format.json { head :no_content }
      else
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo = Repo.find(params[:id])
    @repo.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<h1>Listing repos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>Token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repos.each do |repo| %>
  <tr>
    <td><%= repo.name %></td>
    <td><%= repo.owner %></td>
    <td><%= repo.token %></td>
    <td><%= link_to 'Show', repo %></td>
    <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
    <td><%= link_to 'Destroy', repo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repo', new_repo_path %>

app/views/repos/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @repo.name %>
</p>

<p>
  <b>Owner:</b>
  <%= @repo.owner %>
</p>

<p>
  <b>Token:</b>
  <%= @repo.token %>
</p>


<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>